[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--no-fund --no-audit"

# Optional: SPA fallback (uncomment if you add client-side routing with React Router)
#[[redirects]]
#  from = "/*"
#  to = "/index.html"
#  status = 200
